### ISSUE TITLE
remove wrong suggestion to install terms from dashboard

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property-terms#38]
Those recommendations appear when wp-property installed and terms not

![image](https://user-images.githubusercontent.com/5111163/46014080-d1c9d580-c0d6-11e8-9a71-8121803c2cf4.png)

![image](https://user-images.githubusercontent.com/5111163/46014320-819f4300-c0d7-11e8-9f3d-55b694621696.png)

Need to direct users to our site product page

**Comment by SoSeductive** [comment]
@Mashenka Removed recommendation to install WPP Terms plugin from WP Property composer file

We decide did it because it is easiest way. "Install plugin" link generate with "TGM plugin" in 'wp-lib-bootstrap' lib inside WPP plugin. "TGM" plugin can only do "Install" and "Activate" links and actions. If we change inside "TGM" plugin something we should update 'wp-lib-bootsrap' in all our plugins and later we can't update "TGM"
